title: My Portfolio
logo: /assets/img/Anup_pic.jpeg
description: Consulting & Strategy | Product Management | Solution Architecture | Data Science | AI & ML | FinTech | BFSI | Revenue Management | Cash Management | Payments | Digital Transformation | CSPO | TOGAF® 9 | BIAN | ITIL®
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
